{% set version = "0.7.9" %}

package:
  name: drmaa
  version: {{ version }}

source:
  fn: drmaa-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/drmaa/drmaa-{{ version }}.tar.gz
  sha256: 12540cd98afc40d5c0b2f38d7b0e46468d1c45192a2f401f41fc2eda9c9f5542

build:
  number: 1001
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python

test:
  files:
    - run_test.py
  commands:
    - python run_test.py

about:
  home: https://github.com/pygridtools/drmaa-python
  license: BSD 3-Clause
  license_file: license.txt
  summary: Python wrapper around the C DRMAA library.

extra:
  recipe-maintainers:
    - dan-blanchard
    - jakirkham
