appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: DZ8RfwBVORr3t1Q2ppFcZJ92+BSlfym3EY00J/aZhajzQKcmAiQxDcH93jRYYLVUA/8hPG5mNBG8hEimf5ypFTaitg6RsTRRklUaqyiYSMa70wYmqVMQoAc4541ha8kM0zqDLdI3vmXSNHqSob1o6h/9QJNsKXEPlvfEbSi3Ha2oo6NkZFJt1t/hiYjX5w3jIV1ATg++ZKpjbpHvKsJ995T0H3/f197Pz1u+D3Ok7YlEPl9gryzXWPy2c56iZuPp0LUUMSZk2yk0cUepPYoBr7X7d21POy278ItU+VCx3sVBAAvGw+9JKNHQyAz8uO7dWVgzzAEqRLrp0MTo3CFdSD2njBaaWDUmJb4QBP3D1aQ3YE0lyevzMwuBPH6ypl53S0AWthaKnS/xEwX1TWv9bYl+U+1v590PPb9K0e8tVysOBikWIJqhvsy5DfKo7wFVPDcXSRAfWfkaaI8Zc6M0RsYju9m6iNAIvzbhL+NNLaaxNtEEXm0pqpHoNKiIVShR+1IvI1gqSvRM9LKpf8KfIxEDvW9xK8YmGZGZ4LblQiYNwSiWKdhuHqbis0Q94ozgXNkfxIhzDn2X/Roq+vz5KI0Ctdvzte+RJE/o3D7U3uknMqUhhiK9YgfJgFk7cBSh0n4xp59Qf70o9OOPtApyxkfb2PlXSsdJZRR0EFQO+uo=}
